/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Register
(
    input C,
    input en,
    input D,
    output Q
);

    reg  state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module DIG_Counter_Nbit
#(
    parameter Bits = 2
)
(
    output [(Bits-1):0] out,
    output ovf,
    input C,
    input en,
    input clr
);
    reg [(Bits-1):0] count;

    always @ (posedge C) begin
        if (clr)
          count <= 'h0;
        else if (en)
          count <= count + 1'b1;
    end

    assign out = count;
    assign ovf = en? &count : 1'b0;

    initial begin
        count = 'h0;
    end
endmodule


module buttonFilter (
  input C,
  input btn,
  output ris,
  output fal
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  assign s1 = (btn ^ s0);
  DIG_Register DIG_Register_i0 (
    .D( btn ),
    .C( C ),
    .en( s3 ),
    .Q( s0 )
  );
  assign s2 = ~ s1;
  DIG_Counter_Nbit #(
    .Bits(16)
  )
  DIG_Counter_Nbit_i1 (
    .en( s1 ),
    .C( C ),
    .clr( s2 ),
    .ovf( s3 )
  );
  assign ris = (s3 & ~ s0);
  assign fal = (s3 & s0);
endmodule
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module DIG_Mul_signed #(
    parameter Bits = 1
)
(
    
      input signed [(Bits-1):0] a,
      input signed [(Bits-1):0] b,
      output signed [(Bits*2-1):0] mul
    
);
    assign mul = a * b;
endmodule

module DIG_ROM_8X1_CarryLUT (
    input [2:0] A,
    input sel,
    output reg [0:0] D
);
    reg [0:0] my_rom [0:7];

    always @ (*) begin
        if (~sel)
            D = 1'hz;
        else
            D = my_rom[A];
    end

    initial begin
        my_rom[0] = 1'ha;
        my_rom[1] = 1'ha;
        my_rom[2] = 1'ha;
        my_rom[3] = 1'h1;
        my_rom[4] = 1'h1;
        my_rom[5] = 1'h1;
        my_rom[6] = 1'h9;
        my_rom[7] = 1'h1;
    end
endmodule

module DIG_BitExtenderSingle #(
    parameter outputBits = 2
)
(
    input in,
    output [(outputBits - 1):0] out
);
    assign out = {outputBits{in}};
endmodule




module Mux_8x1_NBits #(
    parameter Bits = 2
)
(
    input [2:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule

module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module genericSplit16_gen0 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[0] = \lsb? [15];
  assign out[15:1] = \msb? [14:0];
  assign \lsb? [0] = 1'b0;
  assign \lsb? [15:1] = \lsb? [14:0];
  assign \msb? [0] = \msb? [15];
  assign \msb? [15:1] = 15'b0;
endmodule

module genericSplit16_gen1 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[1:0] = \lsb? [15:14];
  assign out[15:2] = \msb? [13:0];
  assign \lsb? [1:0] = 2'b0;
  assign \lsb? [15:2] = \lsb? [13:0];
  assign \msb? [1:0] = \msb? [15:14];
  assign \msb? [15:2] = 14'b0;
endmodule

module genericSplit16_gen2 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[2:0] = \lsb? [15:13];
  assign out[15:3] = \msb? [12:0];
  assign \lsb? [2:0] = 3'b0;
  assign \lsb? [15:3] = \lsb? [12:0];
  assign \msb? [2:0] = \msb? [15:13];
  assign \msb? [15:3] = 13'b0;
endmodule

module genericSplit16_gen3 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[3:0] = \lsb? [15:12];
  assign out[15:4] = \msb? [11:0];
  assign \lsb? [3:0] = 4'b0;
  assign \lsb? [15:4] = \lsb? [11:0];
  assign \msb? [3:0] = \msb? [15:12];
  assign \msb? [15:4] = 12'b0;
endmodule

module genericSplit16_gen4 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[4:0] = \lsb? [15:11];
  assign out[15:5] = \msb? [10:0];
  assign \lsb? [4:0] = 5'b0;
  assign \lsb? [15:5] = \lsb? [10:0];
  assign \msb? [4:0] = \msb? [15:11];
  assign \msb? [15:5] = 11'b0;
endmodule

module genericSplit16_gen5 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[5:0] = \lsb? [15:10];
  assign out[15:6] = \msb? [9:0];
  assign \lsb? [5:0] = 6'b0;
  assign \lsb? [15:6] = \lsb? [9:0];
  assign \msb? [5:0] = \msb? [15:10];
  assign \msb? [15:6] = 10'b0;
endmodule

module genericSplit16_gen6 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[6:0] = \lsb? [15:9];
  assign out[15:7] = \msb? [8:0];
  assign \lsb? [6:0] = 7'b0;
  assign \lsb? [15:7] = \lsb? [8:0];
  assign \msb? [6:0] = \msb? [15:9];
  assign \msb? [15:7] = 9'b0;
endmodule

module genericSplit16_gen7 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[7:0] = \lsb? [15:8];
  assign out[15:8] = \msb? [7:0];
  assign \lsb? [7:0] = 8'b0;
  assign \lsb? [15:8] = \lsb? [7:0];
  assign \msb? [7:0] = \msb? [15:8];
  assign \msb? [15:8] = 8'b0;
endmodule

module genericSplit16_gen8 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[8:0] = \lsb? [15:7];
  assign out[15:9] = \msb? [6:0];
  assign \lsb? [8:0] = 9'b0;
  assign \lsb? [15:9] = \lsb? [6:0];
  assign \msb? [8:0] = \msb? [15:7];
  assign \msb? [15:9] = 7'b0;
endmodule

module genericSplit16_gen9 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[9:0] = \lsb? [15:6];
  assign out[15:10] = \msb? [5:0];
  assign \lsb? [9:0] = 10'b0;
  assign \lsb? [15:10] = \lsb? [5:0];
  assign \msb? [9:0] = \msb? [15:6];
  assign \msb? [15:10] = 6'b0;
endmodule

module genericSplit16_gen10 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[10:0] = \lsb? [15:5];
  assign out[15:11] = \msb? [4:0];
  assign \lsb? [10:0] = 11'b0;
  assign \lsb? [15:11] = \lsb? [4:0];
  assign \msb? [10:0] = \msb? [15:5];
  assign \msb? [15:11] = 5'b0;
endmodule

module genericSplit16_gen11 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[11:0] = \lsb? [15:4];
  assign out[15:12] = \msb? [3:0];
  assign \lsb? [11:0] = 12'b0;
  assign \lsb? [15:12] = \lsb? [3:0];
  assign \msb? [11:0] = \msb? [15:4];
  assign \msb? [15:12] = 4'b0;
endmodule

module genericSplit16_gen12 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[12:0] = \lsb? [15:3];
  assign out[15:13] = \msb? [2:0];
  assign \lsb? [12:0] = 13'b0;
  assign \lsb? [15:13] = \lsb? [2:0];
  assign \msb? [12:0] = \msb? [15:3];
  assign \msb? [15:13] = 3'b0;
endmodule

module genericSplit16_gen13 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[13:0] = \lsb? [15:2];
  assign out[15:14] = \msb? [1:0];
  assign \lsb? [13:0] = 14'b0;
  assign \lsb? [15:14] = \lsb? [1:0];
  assign \msb? [13:0] = \msb? [15:2];
  assign \msb? [15:14] = 2'b0;
endmodule

module genericSplit16_gen14 (
  input [15:0] \lsb? ,
  input [15:0] \msb? ,
  output [15:0] out,
  output [15:0] \lsb? ,
  output [15:0] \msb? 
);
  assign out[14:0] = \lsb? [15:1];
  assign out[15] = \msb? [0];
  assign \lsb? [14:0] = 15'b0;
  assign \lsb? [15] = \lsb? [0];
  assign \msb? [14:0] = \msb? [15:1];
  assign \msb? [15] = 1'b0;
endmodule

module Mux_16x1_NBits #(
    parameter Bits = 2
)
(
    input [3:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    input [(Bits - 1):0] in_8,
    input [(Bits - 1):0] in_9,
    input [(Bits - 1):0] in_10,
    input [(Bits - 1):0] in_11,
    input [(Bits - 1):0] in_12,
    input [(Bits - 1):0] in_13,
    input [(Bits - 1):0] in_14,
    input [(Bits - 1):0] in_15,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            4'h0: out = in_0;
            4'h1: out = in_1;
            4'h2: out = in_2;
            4'h3: out = in_3;
            4'h4: out = in_4;
            4'h5: out = in_5;
            4'h6: out = in_6;
            4'h7: out = in_7;
            4'h8: out = in_8;
            4'h9: out = in_9;
            4'ha: out = in_10;
            4'hb: out = in_11;
            4'hc: out = in_12;
            4'hd: out = in_13;
            4'he: out = in_14;
            4'hf: out = in_15;
            default:
                out = 'h0;
        endcase
    end
endmodule


module shiftLeft (
  input [15:0] in,
  input [15:0] fill,
  input [3:0] shift,
  output [15:0] out,
  output [15:0] \c? 
);
  wire [15:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire [15:0] s4;
  wire [15:0] s5;
  wire [15:0] s6;
  wire [15:0] s7;
  wire [15:0] s8;
  wire [15:0] s9;
  wire [15:0] s10;
  wire [15:0] s11;
  wire [15:0] s12;
  wire [15:0] s13;
  wire [15:0] s14;
  wire [15:0] s15;
  wire [15:0] s16;
  wire [15:0] s17;
  wire [15:0] s18;
  wire [15:0] s19;
  wire [15:0] s20;
  wire [15:0] s21;
  wire [15:0] s22;
  wire [15:0] s23;
  wire [15:0] s24;
  wire [15:0] s25;
  wire [15:0] s26;
  wire [15:0] s27;
  wire [15:0] s28;
  wire [15:0] s29;
  genericSplit16_gen0 genericSplit16_gen0_i0 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s0 ),
    .\msb? ( s15 )
  );
  genericSplit16_gen1 genericSplit16_gen1_i1 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s1 ),
    .\msb? ( s16 )
  );
  genericSplit16_gen2 genericSplit16_gen2_i2 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s2 ),
    .\msb? ( s17 )
  );
  genericSplit16_gen3 genericSplit16_gen3_i3 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s3 ),
    .\msb? ( s18 )
  );
  genericSplit16_gen4 genericSplit16_gen4_i4 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s4 ),
    .\msb? ( s19 )
  );
  genericSplit16_gen5 genericSplit16_gen5_i5 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s5 ),
    .\msb? ( s20 )
  );
  genericSplit16_gen6 genericSplit16_gen6_i6 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s6 ),
    .\msb? ( s21 )
  );
  genericSplit16_gen7 genericSplit16_gen7_i7 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s7 ),
    .\msb? ( s22 )
  );
  genericSplit16_gen8 genericSplit16_gen8_i8 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s8 ),
    .\msb? ( s23 )
  );
  genericSplit16_gen9 genericSplit16_gen9_i9 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s9 ),
    .\msb? ( s24 )
  );
  genericSplit16_gen10 genericSplit16_gen10_i10 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s10 ),
    .\msb? ( s25 )
  );
  genericSplit16_gen11 genericSplit16_gen11_i11 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s11 ),
    .\msb? ( s26 )
  );
  genericSplit16_gen12 genericSplit16_gen12_i12 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s12 ),
    .\msb? ( s27 )
  );
  genericSplit16_gen13 genericSplit16_gen13_i13 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s13 ),
    .\msb? ( s28 )
  );
  genericSplit16_gen14 genericSplit16_gen14_i14 (
    .\lsb? ( fill ),
    .\msb? ( in ),
    .out( s14 ),
    .\msb? ( s29 )
  );
  Mux_16x1_NBits #(
    .Bits(16)
  )
  Mux_16x1_NBits_i15 (
    .sel( shift ),
    .in_0( in ),
    .in_1( s0 ),
    .in_2( s1 ),
    .in_3( s2 ),
    .in_4( s3 ),
    .in_5( s4 ),
    .in_6( s5 ),
    .in_7( s6 ),
    .in_8( s7 ),
    .in_9( s8 ),
    .in_10( s9 ),
    .in_11( s10 ),
    .in_12( s11 ),
    .in_13( s12 ),
    .in_14( s13 ),
    .in_15( s14 ),
    .out( out )
  );
  Mux_16x1_NBits #(
    .Bits(16)
  )
  Mux_16x1_NBits_i16 (
    .sel( shift ),
    .in_0( 16'b0 ),
    .in_1( s15 ),
    .in_2( s16 ),
    .in_3( s17 ),
    .in_4( s18 ),
    .in_5( s19 ),
    .in_6( s20 ),
    .in_7( s21 ),
    .in_8( s22 ),
    .in_9( s23 ),
    .in_10( s24 ),
    .in_11( s25 ),
    .in_12( s26 ),
    .in_13( s27 ),
    .in_14( s28 ),
    .in_15( s29 ),
    .out( \c?  )
  );
endmodule

module shiftRight (
  input [15:0] in,
  input [15:0] fill,
  input [3:0] shift,
  output [15:0] out,
  output [15:0] \c? 
);
  wire [15:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire [15:0] s4;
  wire [15:0] s5;
  wire [15:0] s6;
  wire [15:0] s7;
  wire [15:0] s8;
  wire [15:0] s9;
  wire [15:0] s10;
  wire [15:0] s11;
  wire [15:0] s12;
  wire [15:0] s13;
  wire [15:0] s14;
  wire [15:0] s15;
  wire [15:0] s16;
  wire [15:0] s17;
  wire [15:0] s18;
  wire [15:0] s19;
  wire [15:0] s20;
  wire [15:0] s21;
  wire [15:0] s22;
  wire [15:0] s23;
  wire [15:0] s24;
  wire [15:0] s25;
  wire [15:0] s26;
  wire [15:0] s27;
  wire [15:0] s28;
  wire [15:0] s29;
  genericSplit16_gen14 genericSplit16_gen14_i0 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s0 ),
    .\lsb? ( s15 )
  );
  genericSplit16_gen13 genericSplit16_gen13_i1 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s1 ),
    .\lsb? ( s16 )
  );
  genericSplit16_gen12 genericSplit16_gen12_i2 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s2 ),
    .\lsb? ( s17 )
  );
  genericSplit16_gen11 genericSplit16_gen11_i3 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s3 ),
    .\lsb? ( s18 )
  );
  genericSplit16_gen10 genericSplit16_gen10_i4 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s4 ),
    .\lsb? ( s19 )
  );
  genericSplit16_gen9 genericSplit16_gen9_i5 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s5 ),
    .\lsb? ( s20 )
  );
  genericSplit16_gen8 genericSplit16_gen8_i6 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s6 ),
    .\lsb? ( s21 )
  );
  genericSplit16_gen7 genericSplit16_gen7_i7 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s7 ),
    .\lsb? ( s22 )
  );
  genericSplit16_gen6 genericSplit16_gen6_i8 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s8 ),
    .\lsb? ( s23 )
  );
  genericSplit16_gen5 genericSplit16_gen5_i9 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s9 ),
    .\lsb? ( s24 )
  );
  genericSplit16_gen4 genericSplit16_gen4_i10 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s10 ),
    .\lsb? ( s25 )
  );
  genericSplit16_gen3 genericSplit16_gen3_i11 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s11 ),
    .\lsb? ( s26 )
  );
  genericSplit16_gen2 genericSplit16_gen2_i12 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s12 ),
    .\lsb? ( s27 )
  );
  genericSplit16_gen1 genericSplit16_gen1_i13 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s13 ),
    .\lsb? ( s28 )
  );
  genericSplit16_gen0 genericSplit16_gen0_i14 (
    .\lsb? ( in ),
    .\msb? ( fill ),
    .out( s14 ),
    .\lsb? ( s29 )
  );
  Mux_16x1_NBits #(
    .Bits(16)
  )
  Mux_16x1_NBits_i15 (
    .sel( shift ),
    .in_0( in ),
    .in_1( s0 ),
    .in_2( s1 ),
    .in_3( s2 ),
    .in_4( s3 ),
    .in_5( s4 ),
    .in_6( s5 ),
    .in_7( s6 ),
    .in_8( s7 ),
    .in_9( s8 ),
    .in_10( s9 ),
    .in_11( s10 ),
    .in_12( s11 ),
    .in_13( s12 ),
    .in_14( s13 ),
    .in_15( s14 ),
    .out( out )
  );
  Mux_16x1_NBits #(
    .Bits(16)
  )
  Mux_16x1_NBits_i16 (
    .sel( shift ),
    .in_0( 16'b0 ),
    .in_1( s15 ),
    .in_2( s16 ),
    .in_3( s17 ),
    .in_4( s18 ),
    .in_5( s19 ),
    .in_6( s20 ),
    .in_7( s21 ),
    .in_8( s22 ),
    .in_9( s23 ),
    .in_10( s24 ),
    .in_11( s25 ),
    .in_12( s26 ),
    .in_13( s27 ),
    .in_14( s28 ),
    .in_15( s29 ),
    .out( \c?  )
  );
endmodule

module alu (
  input C,
  input [15:0] a,
  input [15:0] b,
  input [3:0] op,
  input en,
  output [15:0] out
);
  wire [2:0] fun3;
  wire carry;
  wire [15:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire [15:0] s4;
  wire [15:0] s5;
  wire [15:0] s6;
  wire [15:0] \c? ;
  wire s7;
  wire [15:0] s8;
  wire [15:0] \c? ;
  wire [15:0] s9;
  wire [15:0] s10;
  wire sub;
  wire s11;
  wire [31:0] s12;
  wire s13;
  wire [3:0] s14;
  wire [15:0] s15;
  wire [15:0] s16;
  wire [15:0] s17;
  wire s18;
  wire s19;
  wire [15:0] s20;
  wire [15:0] s21;
  wire [15:0] s22;
  DIG_Mul_signed #(
    .Bits(16)
  )
  DIG_Mul_signed_i0 (
    .a( a ),
    .b( b ),
    .mul( s12 )
  );
  assign s0 = (a | b);
  assign s1 = (a & b);
  assign s2 = (a ^ b);
  assign fun3 = op[2:0];
  assign carry = op[3];
  assign s18 = a[15];
  assign s14 = b[3:0];
  // CarryLUT
  DIG_ROM_8X1_CarryLUT DIG_ROM_8X1_CarryLUT_i1 (
    .A( fun3 ),
    .sel( 1'b1 ),
    .D( s19 )
  );
  DIG_BitExtenderSingle #(
    .outputBits(16)
  )
  DIG_BitExtenderSingle_i2 (
    .in( s18 ),
    .out( s22 )
  );
  assign sub = fun3[0];
  assign s3 = s12[15:0];
  assign s21 = s12[31:16];
  DIG_BitExtenderSingle #(
    .outputBits(16)
  )
  DIG_BitExtenderSingle_i3 (
    .in( sub ),
    .out( s9 )
  );
  assign s7 = (s19 & en);
  assign s10 = (b ^ s9);
  Mux_8x1_NBits #(
    .Bits(16)
  )
  Mux_8x1_NBits_i4 (
    .sel( fun3 ),
    .in_0( s0 ),
    .in_1( s1 ),
    .in_2( s2 ),
    .in_3( s3 ),
    .in_4( s4 ),
    .in_5( s4 ),
    .in_6( s5 ),
    .in_7( s6 ),
    .out( out )
  );
  // Carry
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i5 (
    .D( \c?  ),
    .C( C ),
    .en( s7 ),
    .Q( s8 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i6 (
    .sel( carry ),
    .in_0( 16'b0 ),
    .in_1( s8 ),
    .out( \c?  )
  );
  assign s11 = (\c? [0] ^ sub);
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i7 (
    .a( a ),
    .b( s10 ),
    .c_i( s11 ),
    .s( s4 ),
    .c_o( s13 )
  );
  shiftLeft shiftLeft_i8 (
    .in( a ),
    .fill( \c?  ),
    .shift( s14 ),
    .out( s5 ),
    .\c? ( s15 )
  );
  shiftRight shiftRight_i9 (
    .in( a ),
    .fill( s16 ),
    .shift( s14 ),
    .out( s17 ),
    .\c? ( s6 )
  );
  Mux_8x1_NBits #(
    .Bits(16)
  )
  Mux_8x1_NBits_i10 (
    .sel( fun3 ),
    .in_0( 16'b0 ),
    .in_1( 16'b0 ),
    .in_2( 16'b0 ),
    .in_3( s21 ),
    .in_4( s20 ),
    .in_5( s20 ),
    .in_6( s15 ),
    .in_7( s17 ),
    .out( \c?  )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i11 (
    .sel( carry ),
    .in_0( s22 ),
    .in_1( \c?  ),
    .out( s16 )
  );
  assign s20[0] = s13;
  assign s20[15:1] = 15'b0;
endmodule
module DIG_ROM_8192X16_Program (
    input [12:0] A,
    input sel,
    output reg [15:0] D
);
    reg [15:0] my_rom [0:7];

    always @ (*) begin
        if (~sel)
            D = 16'hz;
        else if (A > 13'h7)
            D = 16'h0;
        else
            D = my_rom[A];
    end

    initial begin
        my_rom[0] = 16'h26;
        my_rom[1] = 16'hdead;
        my_rom[2] = 16'h440f;
        my_rom[3] = 16'hffff;
        my_rom[4] = 16'h26;
        my_rom[5] = 16'hbeef;
        my_rom[6] = 16'h440f;
        my_rom[7] = 16'hffff;
    end
endmodule

module DIG_ROM_8192X16_Data (
    input [12:0] A,
    input sel,
    output reg [15:0] D
);
    reg [15:0] my_rom [0:-1];

    always @ (*) begin
        if (~sel)
            D = 16'hz;
        else if (A > 13'hffffffffffffffff)
            D = 16'h0;
        else
            D = my_rom[A];
    end

    initial begin
    end
endmodule

module DIG_RAMDualPort
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
  input [(AddrBits-1):0] A,
  input [(Bits-1):0] Din,
  input str,
  input C,
  input ld,
  output [(Bits-1):0] D
);
  reg [(Bits-1):0] memory[0:((1 << AddrBits) - 1)];

  assign D = ld? memory[A] : 'hz;

  always @ (posedge C) begin
    if (str)
      memory[A] <= Din;
  end
endmodule


module addressSpace (
  input C,
  input [15:0] Ia,
  input [15:0] Da,
  input [15:0] Din,
  input str,
  output [15:0] I,
  output [15:0] D
);
  wire [12:0] s0;
  wire [12:0] s1;
  wire [15:0] s2;
  wire Data_High;
  wire s3;
  wire [15:0] s4;
  wire Inst_High;
  assign s1 = Da[12:0];
  assign Data_High = Da[13];
  assign s0 = Ia[12:0];
  assign Inst_High = Ia[13];
  // Program
  DIG_ROM_8192X16_Program DIG_ROM_8192X16_Program_i0 (
    .A( s0 ),
    .sel( 1'b1 ),
    .D( I )
  );
  // Data
  DIG_ROM_8192X16_Data DIG_ROM_8192X16_Data_i1 (
    .A( s1 ),
    .sel( 1'b1 ),
    .D( s2 )
  );
  assign s3 = (str & Data_High);
  DIG_RAMDualPort #(
    .Bits(16),
    .AddrBits(13)
  )
  DIG_RAMDualPort_i2 (
    .A( s1 ),
    .Din( Din ),
    .str( s3 ),
    .C( C ),
    .ld( 1'b1 ),
    .D( s4 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i3 (
    .sel( Data_High ),
    .in_0( s2 ),
    .in_1( s4 ),
    .out( D )
  );
endmodule

module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule

module DIG_RegisterFile
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
    input [(Bits-1):0] Din,
    input we,
    input [(AddrBits-1):0] Rw,
    input C,
    input [(AddrBits-1):0] Ra,
    input [(AddrBits-1):0] Rb,
    output [(Bits-1):0] Da,
    output [(Bits-1):0] Db
);

    reg [(Bits-1):0] memory[0:((1 << AddrBits)-1)];

    assign Da = memory[Ra];
    assign Db = memory[Rb];

    always @ (posedge C) begin
        if (we)
            memory[Rw] <= Din;
    end
endmodule

module DIG_ROM_16X1_ExtendedLUT (
    input [3:0] A,
    input sel,
    output reg [0:0] D
);
    reg [0:0] my_rom [0:13];

    always @ (*) begin
        if (~sel)
            D = 1'hz;
        else if (A > 4'hd)
            D = 1'h0;
        else
            D = my_rom[A];
    end

    initial begin
        my_rom[0] = 1'h0;
        my_rom[1] = 1'h0;
        my_rom[2] = 1'h0;
        my_rom[3] = 1'h0;
        my_rom[4] = 1'h1;
        my_rom[5] = 1'h0;
        my_rom[6] = 1'h1;
        my_rom[7] = 1'h0;
        my_rom[8] = 1'h0;
        my_rom[9] = 1'h0;
        my_rom[10] = 1'h0;
        my_rom[11] = 1'h0;
        my_rom[12] = 1'h0;
        my_rom[13] = 1'h1;
    end
endmodule


module eTypeBuffer (
  input [15:0] I,
  input C,
  output [31:0] Iext
);
  wire [15:0] s0;
  wire [3:0] s1;
  wire s2;
  wire s3;
  wire [15:0] s4;
  wire s5;
  wire s6;
  wire [15:0] s7;
  // LowerWord
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i0 (
    .D( I ),
    .C( C ),
    .en( s3 ),
    .Q( s4 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i1 (
    .sel( s5 ),
    .in_0( I ),
    .in_1( s4 ),
    .out( s0 )
  );
  assign Iext[15:0] = s7;
  assign Iext[31:16] = I;
  assign s1 = s0[3:0];
  // ExtendedLUT
  DIG_ROM_16X1_ExtendedLUT DIG_ROM_16X1_ExtendedLUT_i2 (
    .A( s1 ),
    .sel( 1'b1 ),
    .D( s2 )
  );
  assign s3 = (s2 & s6);
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i3 (
    .sel( s3 ),
    .in_0( s0 ),
    .in_1( 16'b0 ),
    .out( s7 )
  );
  // IsExtended
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i4 (
    .D( s3 ),
    .C( C ),
    .Q( s5 ),
    .\~Q ( s6 )
  );
endmodule
module DIG_ROM_32X22_OpcodeLUT (
    input [4:0] A,
    input sel,
    output reg [21:0] D
);
    reg [21:0] my_rom [0:23];

    always @ (*) begin
        if (~sel)
            D = 22'hz;
        else if (A > 5'h17)
            D = 22'h0;
        else
            D = my_rom[A];
    end

    initial begin
        my_rom[0] = 22'h4080;
        my_rom[1] = 22'h4180;
        my_rom[2] = 22'h4281;
        my_rom[3] = 22'hc284;
        my_rom[4] = 22'h428c;
        my_rom[5] = 22'h4e0b;
        my_rom[6] = 22'h4e0c;
        my_rom[7] = 22'h5247;
        my_rom[8] = 22'h10246;
        my_rom[9] = 22'h50601;
        my_rom[10] = 22'h1060b;
        my_rom[11] = 22'h10241;
        my_rom[12] = 22'h1660b;
        my_rom[13] = 22'h1620c;
        my_rom[14] = 22'h84281;
        my_rom[15] = 22'h0;
        my_rom[16] = 22'h7001;
        my_rom[17] = 22'h100001;
        my_rom[18] = 22'h0;
        my_rom[19] = 22'h0;
        my_rom[20] = 22'h0;
        my_rom[21] = 22'h0;
        my_rom[22] = 22'h0;
        my_rom[23] = 22'h200000;
    end
endmodule

module DIG_BitExtender #(
    parameter inputBits = 2,
    parameter outputBits = 4
)
(
    input [(inputBits-1):0] in,
    output [(outputBits - 1):0] out
);
    assign out = {{(outputBits - inputBits){in[inputBits - 1]}}, in};
endmodule




module decoder (
  input C,
  input [15:0] I,
  output [15:0] imm,
  output [1:0] ALUaS,
  output ALUbS,
  output [3:0] ALUo,
  output [1:0] Dsrc,
  output we,
  output [2:0] Rw,
  output [2:0] Ra,
  output [2:0] Rb,
  output str,
  output jmp,
  output [2:0] CmpO,
  output out,
  output hault
);
  wire [31:0] s0;
  wire [3:0] s1;
  wire [2:0] rd;
  wire [2:0] Rb_temp;
  wire [2:0] fun3;
  wire [2:0] Ra_temp;
  wire [15:0] s2;
  wire [4:0] s3;
  wire [21:0] s4;
  wire s5;
  wire [4:0] s6;
  wire [4:0] s7;
  wire \imm[2:0]_select ;
  wire [2:0] s8;
  wire \imm[5:3]_select ;
  wire [1:0] imm_size;
  wire [2:0] default_ALUo;
  wire use_fun3_as_ALUo;
  wire write_to_rs1;
  wire conditional_jump;
  wire [2:0] s9;
  wire [15:0] s10;
  wire [15:0] s11;
  wire [15:0] s12;
  wire [15:0] s13;
  wire [5:0] s14;
  wire [8:0] s15;
  wire [2:0] s16;
  wire [15:0] s17;
  eTypeBuffer eTypeBuffer_i0 (
    .I( I ),
    .C( C ),
    .Iext( s0 )
  );
  assign s1 = s0[3:0];
  assign rd = s0[6:4];
  assign Rb_temp = s0[9:7];
  assign fun3 = s0[12:10];
  assign Ra_temp = s0[15:13];
  assign s2 = s0[31:16];
  assign s5 = (s1[3] & s1[2] & s1[1] & s1[0]);
  assign s6[3:0] = s1;
  assign s6[4] = 1'b0;
  assign s7[2:0] = fun3;
  assign s7[4:3] = 2'b10;
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i1 (
    .sel( s5 ),
    .in_0( s6 ),
    .in_1( s7 ),
    .out( s3 )
  );
  // OpcodeLUT
  DIG_ROM_32X22_OpcodeLUT DIG_ROM_32X22_OpcodeLUT_i2 (
    .A( s3 ),
    .sel( 1'b1 ),
    .D( s4 )
  );
  assign s17[2:0] = 3'b0;
  assign s17[3] = s4[19];
  assign s17[15:4] = 12'b0;
  assign \imm[2:0]_select  = s4[0];
  assign \imm[5:3]_select  = s4[1];
  assign imm_size = s4[3:2];
  assign default_ALUo = s4[6:4];
  assign use_fun3_as_ALUo = s4[7];
  assign ALUbS = s4[9];
  assign ALUaS = s4[11:10];
  assign Dsrc = s4[13:12];
  assign we = s4[14];
  assign write_to_rs1 = s4[15];
  assign str = s4[16];
  assign jmp = s4[17];
  assign conditional_jump = s4[18];
  assign out = s4[20];
  assign hault = s4[21];
  Mux_2x1_NBits #(
    .Bits(3)
  )
  Mux_2x1_NBits_i3 (
    .sel( \imm[2:0]_select  ),
    .in_0( rd ),
    .in_1( Rb_temp ),
    .out( s8 )
  );
  Mux_2x1_NBits #(
    .Bits(3)
  )
  Mux_2x1_NBits_i4 (
    .sel( \imm[5:3]_select  ),
    .in_0( Rb_temp ),
    .in_1( fun3 ),
    .out( s9 )
  );
  Mux_2x1_NBits #(
    .Bits(3)
  )
  Mux_2x1_NBits_i5 (
    .sel( use_fun3_as_ALUo ),
    .in_0( default_ALUo ),
    .in_1( fun3 ),
    .out( s16 )
  );
  Mux_2x1_NBits #(
    .Bits(3)
  )
  Mux_2x1_NBits_i6 (
    .sel( write_to_rs1 ),
    .in_0( rd ),
    .in_1( Ra_temp ),
    .out( Rw )
  );
  Mux_2x1_NBits #(
    .Bits(3)
  )
  Mux_2x1_NBits_i7 (
    .sel( conditional_jump ),
    .in_0( 3'b111 ),
    .in_1( fun3 ),
    .out( CmpO )
  );
  DIG_BitExtender #(
    .inputBits(3),
    .outputBits(16)
  )
  DIG_BitExtender_i8 (
    .in( s8 ),
    .out( s10 )
  );
  assign s14[2:0] = s8;
  assign s14[5:3] = s9;
  assign ALUo[2:0] = s16;
  assign ALUo[3] = s4[8];
  DIG_BitExtender #(
    .inputBits(6),
    .outputBits(16)
  )
  DIG_BitExtender_i9 (
    .in( s14 ),
    .out( s11 )
  );
  assign s15[5:0] = s14;
  assign s15[8:6] = Ra_temp;
  DIG_BitExtender #(
    .inputBits(9),
    .outputBits(16)
  )
  DIG_BitExtender_i10 (
    .in( s15 ),
    .out( s12 )
  );
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i11 (
    .sel( imm_size ),
    .in_0( s10 ),
    .in_1( s11 ),
    .in_2( s12 ),
    .in_3( s2 ),
    .out( s13 )
  );
  assign imm = (s17 ^ s13);
  assign Ra = Ra_temp;
  assign Rb = Rb_temp;
endmodule

module comparator (
  input [15:0] val,
  input [2:0] op,
  output out
);
  assign out = ((~ (val[15] | ~ (val[0] | val[1] | val[2] | val[3] | val[4] | val[5] | val[6] | val[7] | val[9] | val[10] | val[11] | val[12] | val[13] | val[14] | val[15] | val[8])) & op[2]) | (~ (val[0] | val[1] | val[2] | val[3] | val[4] | val[5] | val[6] | val[7] | val[9] | val[10] | val[11] | val[12] | val[13] | val[14] | val[15] | val[8]) & op[1]) | (val[15] & op[0]));
endmodule

module Demux3
#(
    parameter Default = 0 
)
(
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    input [2:0] sel,
    input in
);
    assign out_0 = (sel == 3'h0)? in : Default;
    assign out_1 = (sel == 3'h1)? in : Default;
    assign out_2 = (sel == 3'h2)? in : Default;
    assign out_3 = (sel == 3'h3)? in : Default;
    assign out_4 = (sel == 3'h4)? in : Default;
    assign out_5 = (sel == 3'h5)? in : Default;
    assign out_6 = (sel == 3'h6)? in : Default;
    assign out_7 = (sel == 3'h7)? in : Default;
endmodule


module Demux2
#(
    parameter Default = 0 
)
(
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    input [1:0] sel,
    input in
);
    assign out_0 = (sel == 2'h0)? in : Default;
    assign out_1 = (sel == 2'h1)? in : Default;
    assign out_2 = (sel == 2'h2)? in : Default;
    assign out_3 = (sel == 2'h3)? in : Default;
endmodule

module DIG_ROM_16X7_Digits (
    input [3:0] A,
    input sel,
    output reg [6:0] D
);
    reg [6:0] my_rom [0:15];

    always @ (*) begin
        if (~sel)
            D = 7'hz;
        else
            D = my_rom[A];
    end

    initial begin
        my_rom[0] = 7'h40;
        my_rom[1] = 7'h79;
        my_rom[2] = 7'h24;
        my_rom[3] = 7'h30;
        my_rom[4] = 7'h19;
        my_rom[5] = 7'h12;
        my_rom[6] = 7'h2;
        my_rom[7] = 7'h58;
        my_rom[8] = 7'h0;
        my_rom[9] = 7'h10;
        my_rom[10] = 7'h8;
        my_rom[11] = 7'h3;
        my_rom[12] = 7'h27;
        my_rom[13] = 7'h21;
        my_rom[14] = 7'h6;
        my_rom[15] = 7'he;
    end
endmodule


module hexDisplayDriver (
  input Cl,
  input [15:0] num,
  output a,
  output b,
  output c,
  output d,
  output e,
  output f,
  output g,
  output W,
  output X,
  output Y,
  output Z
);
  wire [3:0] s0;
  wire [6:0] s1;
  wire [5:0] s2;
  wire [3:0] s3;
  wire [3:0] s4;
  wire [3:0] s5;
  wire [3:0] s6;
  wire [1:0] s7;
  wire s8;
  wire s9;
  DIG_Counter_Nbit #(
    .Bits(6)
  )
  DIG_Counter_Nbit_i0 (
    .en( 1'b1 ),
    .C( Cl ),
    .clr( 1'b0 ),
    .out( s2 )
  );
  assign s3 = num[3:0];
  assign s4 = num[7:4];
  assign s5 = num[11:8];
  assign s6 = num[15:12];
  assign s9 = ~ (s2[1] & s2[3]);
  assign s8 = s2[2];
  assign s7 = s2[5:4];
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i1 (
    .sel( s7 ),
    .in_0( s3 ),
    .in_1( s4 ),
    .in_2( s5 ),
    .in_3( s6 ),
    .out( s0 )
  );
  Demux2 #(
    .Default(0)
  )
  Demux2_i2 (
    .sel( s7 ),
    .in( s9 ),
    .out_0( W ),
    .out_1( X ),
    .out_2( Y ),
    .out_3( Z )
  );
  // Digits
  DIG_ROM_16X7_Digits DIG_ROM_16X7_Digits_i3 (
    .A( s0 ),
    .sel( 1'b1 ),
    .D( s1 )
  );
  assign a = s1[0];
  assign b = s1[1];
  assign c = s1[2];
  assign d = s1[3];
  assign e = s1[4];
  assign f = s1[5];
  assign g = s1[6];
endmodule

module canis (
  input CLK,
  input PIN_13,
  output PIN_22,
  output PIN_24,
  output PIN_21,
  output PIN_18,
  output PIN_19,
  output PIN_20,
  output PIN_23,
  output PIN_15,
  output PIN_14,
  output PIN_17,
  output PIN_16
);
  wire [15:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire [3:0] s4;
  wire s5;
  wire [15:0] s6;
  wire [15:0] s7;
  wire [15:0] s8;
  wire s9;
  wire [15:0] s10;
  wire [15:0] s11;
  wire [15:0] s12;
  wire [1:0] s13;
  wire s14;
  wire [1:0] s15;
  wire s16;
  wire [2:0] s17;
  wire [2:0] s18;
  wire [2:0] s19;
  wire s20;
  wire s21;
  wire [2:0] s22;
  wire s23;
  wire s24;
  wire [15:0] s25;
  wire [15:0] s26;
  wire s27;
  wire [15:0] s28;
  wire s29;
  wire s30;
  wire [2:0] s31;
  wire s32;
  wire [15:0] s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire [15:0] s41;
  wire [15:0] s42;
  wire [15:0] s43;
  wire [15:0] s44;
  wire [15:0] s45;
  wire [15:0] s46;
  wire [15:0] s47;
  wire s48;
  wire s49;
  wire s50;
  buttonFilter buttonFilter_i0 (
    .C( CLK ),
    .btn( PIN_13 ),
    .ris( s50 )
  );
  assign s49 = (~ s50 & (s48 | s24));
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( s49 ),
    .C( CLK ),
    .Q( s48 )
  );
  assign s5 = ~ s49;
  alu alu_i2 (
    .C( CLK ),
    .a( s2 ),
    .b( s3 ),
    .op( s4 ),
    .en( s5 ),
    .out( s6 )
  );
  // PC
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i3 (
    .D( s7 ),
    .C( CLK ),
    .en( s5 ),
    .Q( s0 )
  );
  assign s9 = (s20 & s5);
  assign s27 = (s16 & s5);
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i4 (
    .a( s0 ),
    .b( 16'b1 ),
    .c_i( 1'b0 ),
    .s( s1 )
  );
  addressSpace addressSpace_i5 (
    .C( CLK ),
    .Ia( s0 ),
    .Da( s6 ),
    .Din( s8 ),
    .str( s9 ),
    .I( s10 ),
    .D( s11 )
  );
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i6 (
    .sel( s15 ),
    .in_0( s6 ),
    .in_1( s11 ),
    .in_2( s1 ),
    .in_3( s25 ),
    .out( s26 )
  );
  // Registers
  DIG_RegisterFile #(
    .Bits(16),
    .AddrBits(3)
  )
  DIG_RegisterFile_i7 (
    .Din( s26 ),
    .we( s27 ),
    .Rw( s17 ),
    .C( CLK ),
    .Ra( s18 ),
    .Rb( s19 ),
    .Da( s28 ),
    .Db( s8 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i8 (
    .sel( s30 ),
    .in_0( s1 ),
    .in_1( s6 ),
    .out( s7 )
  );
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i9 (
    .sel( s13 ),
    .in_0( s28 ),
    .in_1( s1 ),
    .in_2( 16'b0 ),
    .in_3( 16'b0 ),
    .out( s2 )
  );
  decoder decoder_i10 (
    .C( CLK ),
    .I( s10 ),
    .imm( s12 ),
    .ALUaS( s13 ),
    .ALUbS( s14 ),
    .ALUo( s4 ),
    .Dsrc( s15 ),
    .we( s16 ),
    .Rw( s17 ),
    .Ra( s18 ),
    .Rb( s19 ),
    .str( s20 ),
    .jmp( s21 ),
    .CmpO( s22 ),
    .out( s23 ),
    .hault( s24 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i11 (
    .sel( s14 ),
    .in_0( s8 ),
    .in_1( s12 ),
    .out( s3 )
  );
  comparator comparator_i12 (
    .val( s28 ),
    .op( s22 ),
    .out( s29 )
  );
  assign s31 = s12[2:0];
  assign s30 = (s29 & s21);
  Mux_8x1_NBits #(
    .Bits(16)
  )
  Mux_8x1_NBits_i13 (
    .sel( s31 ),
    .in_0( 16'b0 ),
    .in_1( 16'b0 ),
    .in_2( 16'b0 ),
    .in_3( 16'b0 ),
    .in_4( 16'b0 ),
    .in_5( 16'b0 ),
    .in_6( 16'b0 ),
    .in_7( 16'b0 ),
    .out( s25 )
  );
  Demux3 #(
    .Default(0)
  )
  Demux3_i14 (
    .sel( s31 ),
    .in( s23 ),
    .out_0( s34 ),
    .out_1( s35 ),
    .out_2( s36 ),
    .out_3( s37 ),
    .out_4( s38 ),
    .out_5( s39 ),
    .out_6( s32 ),
    .out_7( s40 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i15 (
    .D( s28 ),
    .C( CLK ),
    .en( s32 ),
    .Q( s33 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i16 (
    .D( s28 ),
    .C( CLK ),
    .en( s40 ),
    .Q( s41 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i17 (
    .D( s28 ),
    .C( CLK ),
    .en( s38 ),
    .Q( s42 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i18 (
    .D( s28 ),
    .C( CLK ),
    .en( s39 ),
    .Q( s43 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i19 (
    .D( s28 ),
    .C( CLK ),
    .en( s36 ),
    .Q( s44 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i20 (
    .D( s28 ),
    .C( CLK ),
    .en( s37 ),
    .Q( s45 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i21 (
    .D( s28 ),
    .C( CLK ),
    .en( s34 ),
    .Q( s46 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i22 (
    .D( s28 ),
    .C( CLK ),
    .en( s35 ),
    .Q( s47 )
  );
  hexDisplayDriver hexDisplayDriver_i23 (
    .Cl( CLK ),
    .num( s46 ),
    .a( PIN_22 ),
    .b( PIN_24 ),
    .c( PIN_21 ),
    .d( PIN_18 ),
    .e( PIN_19 ),
    .f( PIN_20 ),
    .g( PIN_23 ),
    .W( PIN_15 ),
    .X( PIN_14 ),
    .Y( PIN_17 ),
    .Z( PIN_16 )
  );
endmodule
